export const DISPLAY_LOADING = "DISPLAY_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

// BASIC
export const LOGIN = "LOGIN";

export const GET_DESTINATION = "GET_DESTINATION";

// FREELANCER PROFILE

export const GET_TOUR_GUIDE_BY_ID_GUIDE = "GET_TOUR_GUIDE_BY_ID_GUIDE";

export const GET_GUIDE_LANGUAGUE_BY_ID_GUIDE = "GET_GUIDE_LANGUAGUE_BY_ID_GUIDE";

export const GET_GUIDE_LICENSE_BY_ID_GUIDE = "GET_GUIDE_LICENSE_BY_ID_GUIDE";

export const UPDATE_GUIDE_INFO = "UPDATE_GUIDE_INFO";

export const UPDATE_GUIDE_LANGUAGE = "UPDATE_GUIDE_LANGUAGE";

export const UPDATE_GUIDE_AVATAR = "UPDATE_GUIDE_AVATAR";

export const UPDATE_GUIDE_LICENSE = "UPDATE_GUIDE_LICENSE";

export const UPDATE_UPLOADED_LICENSE = "UPDATE_UPLOADED_LICENSE";

export const GET_GUIDE_ATTRACTION_BY_ID_GUIDE = "GET_GUIDE_ATTRACTION_BY_ID_GUIDE";

// FREELANCER CALENDAR

export const GET_GUIDE_TIME_BY_ID_GUIDE = "GET_GUIDE_TIME_BY_ID_GUIDE";

export const UPDATE_GUIDE_TIME_BY_ID_GUIDE = "UPDATE_GUIDE_TIME_BY_ID_GUIDE";

// FREELANCER STATISITC

export const GET_GUIDE_BOOKING_BY_ID_GUIDE = "GET_GUIDE_BOOKING_BY_ID_GUIDE";

export const GET_GUIDE_REVIEW_BY_ID_GUIDEBOOKING = "GET_GUIDE_REVIEW_BY_ID_GUIDEBOOK"


// COMPANY PROFILE

export const GET_COMPANY_INFO= "GET_COMPANY_INFO";

export const GET_GOMPANY_LICENSE = "GET_GOMPANY_LICENSE";

export const UPDATE_COMPANY_INFO = "UPDATE_COMPANY_INFO";

export const UPDATE_COMPANY_LICENSE = "UPDATE_COMPANY_LICENSE";

// COMPANY TOUR

export const GET_TOUR_BY_ID_COMPANY = "GET_TOUR_BY_ID_COMPANY";

export const ADD_TOUR_BY_ID_COMPANY = "ADD_TOUR_BY_ID_COMPANY";

export const UPDATE_TOUR_BY_ID_TOUR = "UPDATE_TOUR_BY_ID_TOUR";

export const DELETE_TOUR_BY_ID_TOUR = "DELETE_TOUR_BY_ID_TOUR"

// COMPANY STATISITC

// ???
export const GET_COMPANY_BOOKING = "GET_COMPANY_BOOKING";

export const GET_COMPANY_REVIEW = "GET_COMPANY_REVIEW";














