export const DISPLAY_LOADING = "DISPLAY_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

// FREELANCER PROFILE
export const GET_TOUR_GUIDE_BY_ID_GUIDE = "GET_TOUR_GUIDE_BY_ID_GUIDE"; 

export const GET_GUIDE_LANGUAGUE_BY_ID_GUIDE = "GET_GUIDE_LANGUAGUE_BY_ID_GUIDE";

export const GET_GUIDE_LICENSE_BY_ID_GUIDE = "GET_GUIDE_LICENSE_BY_ID_GUIDE";

export const UPDATE_TOUR_GUIDE_BY_ID_GUIDE = "UPDATE_TOUR_GUIDE_BY_ID_GUIDE";

export const GET_GUIDE_ATTRACTION_BY_ID_GUIDE = "GET_GUIDE_ATTRACTION_BY_ID_GUIDE";

export const UPDATE_GUIDE_ATTRACTION_BY_ID_GUIDE = "UPDATE_GUIDE_ATTRACTION_BY_ID_GUIDE";

export const GET_DESTINATION = "GET_DESTINATION";
